version: '3.3'

services:
  node:
    image: node:8.9.3
    volumes:
      - ./:/app
    tty: true
    working_dir: /app
    environment:
      - COVERALLS_REPO_TOKEN

  docs:
    build: ./docker/mkdocs
    volumes:
      - ./:/app
    working_dir: /app
    tty: true