site_name: Pangea
site_url: https://bitnation.co
repo_url: https://github.com/Bit-Nation/BITNATION-Pangea-mobile
site_dir: docs_build
pages:
  - Getting Started: getting_started.md
  - How to contribute: contribute.md
  - DApp Development (native): dapp_dev_native.md
  - DApp Development (VM): dapp_dev_vm.md
theme: readthedocs
