site_name: Bitnation Pangea
site_url: https://bitnation.co
repo_url: https://github.com/Bit-Nation/BITNATION-Pangea-mobile
site_dir: docs_build
pages:
  - Home: index.md
  - Tech stack & high level overview: tech_stack_and_high_level_overview.md
  - Services: services.md
  - Components: components.md
  - Extend the docs: work_on_docs.md

theme: readthedocs