export default {
  BITNATION: require('pangea-common-reactnative/assets/images/bitnation.png'),
  Catalunya: require('pangea-common-reactnative/assets/images/Catalunya.png'),
  'Digital Nomads': require('pangea-common-reactnative/assets/images/digital-nomad-nation.png'),
  'De Pijp Nation': require('pangea-common-reactnative/assets/images/de-pijp-nation.png'),
  Liberland: require('pangea-common-reactnative/assets/images/liberland.png'),
  'TEDx ': require('pangea-common-reactnative/assets/images/TEDx-Nation.png'),
  'TAZ Nation': require('pangea-common-reactnative/assets/images/TAZ-Nation.png'),
  'Serenissima Republic of Venice': require('pangea-common-reactnative/assets/images/erinissima-republic-of-Venice.png'),
  WeedNation: require('pangea-common-reactnative/assets/images/weednation.png'),
  Ancap: require('pangea-common-reactnative/assets/images/Ancap.png'),
  'Family Protection ': require('pangea-common-reactnative/assets/images/family-protection.png'),
  Anonymous: require('pangea-common-reactnative/assets/images/Anonymous.png'),
  AVALON: require('pangea-common-reactnative/assets/images/AVALON.png'),
  World: require('pangea-common-reactnative/assets/images/World.png'),
  default: require('pangea-common-reactnative/assets/images/default.png'),
  '1-Blockchain world': require('pangea-common-reactnative/assets/images/1-BlockChain-world.png'),
  'Network Society': require('pangea-common-reactnative/assets/images/Network-Society.png'),
  'Ideias Radicais': require('pangea-common-reactnative/assets/images/Ideais-Radicais.png'),
  'República Catalana': require('pangea-common-reactnative/assets/images/Catalunya.png'),
};
