export const KEY_PAGE_ROW_COUNT = 4;
export const KEY_PAGE_COUNT = 2;
export const KEY_COLUMN_COUNT = 3;
export const KEY_PAGE_LENGTH = KEY_PAGE_ROW_COUNT * KEY_COLUMN_COUNT;
export const KEY_ROW_COUNT = KEY_PAGE_ROW_COUNT * KEY_PAGE_COUNT;
export const KEY_LENGTH = KEY_COLUMN_COUNT * KEY_ROW_COUNT;


export const CONNECTION_TIMEOUT = 30 * 1000;