platform :ios, '8.0'

target 'Pangea' do
  
  pod 'RSKImageCropper', '2.0.0'
  pod 'QBImagePickerController', '3.4.0'

  pod 'react-native-zendesk-support', :path => '../node_modules/@synapsestudios/react-native-zendesk-support'

end

