platform :ios, '8.0'

target 'Pangea' do
  
  pod 'RSKImageCropper', '2.0.0'
  pod 'QBImagePickerController', '3.4.0'

  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

end

