
// Objective-C API for talking to the following Go packages
//
//	github.com/Bit-Nation/panthalassa
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Panthalassa_FRAMEWORK_H__
#define __Panthalassa_FRAMEWORK_H__

#include "Panthalassa.objc.h"
#include "universe.objc.h"

#endif
