export default {
  BITNATION: require('../../assets/images/nations/bitnation.png'),
  Catalunya: require('../../assets/images/nations/Catalunya.png'),
  'Digital Nomads': require('../../assets/images/nations/digital nomad nation.png'),
  'De Pijp Nation': require('../../assets/images/nations/de pijp nation.png'),
  Liberland: require('../../assets/images/nations/liberland.png'),
  TEDx: require('../../assets/images/nations/TEDx Nation.png'),
  'TAZ Nation': require('../../assets/images/nations/TAZ Nation.png'),
  'Serenissima Republic of Venice': require('../../assets/images/nations/erinissima republic of Venice.png'),
  WeedNation: require('../../assets/images/nations/weednation.png'),
  Ancap: require('../../assets/images/nations/Ancap.png'),
  'Family Protection': require('../../assets/images/nations/family protection.png'),
  Anonymous: require('../../assets/images/nations/Anonymous.png'),
  AVALON: require('../../assets/images/nations/AVALON.png'),
  World: require('../../assets/images/nations/World.png'),
  default: require('../../assets/images/nations/default.png'),
  '1-BlockChain world': require('../../assets/images/nations/1-BlockChain world.png'),
  'Network Society': require('../../assets/images/nations/Network Society.png'),
  'Ideais Radicais': require('../../assets/images/nations/Ideais Radicais.png'),
};
